data_dir: data/
output_dir: output/
log_dir: logs/
model_type: flaubert
model_name_or_path: flaubert-base-uncased
task_name: ron
config_name:  ""
tokenizer_name: ""
cache_dir: ""
max_seq_length: 128
do_train: True
do_eval: True
evaluate_during_training: True
do_lower_case: False
per_gpu_train_batch_size: 16
per_gpu_eval_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 2e-5
weight_decay: 0.0
adam_epsilon: 1e-8
max_grad_norm: 1.0
num_train_epochs: 2.0
max_steps: -1
warmup_steps: 0
logging_steps: 50
save_steps: 500
eval_all_checkpoints: True
no_cuda: False
overwrite_output_dir: True
overwrite_cache: False
seed: 42
fp16: False
fp16_opt_level: "O1"
local_rank: -1
server_ip: ""
server_port: ""
